name: 'cURL Action AxiosJS'
description: 'cURL action to perform REST API based on Axios'
inputs:
  url: 
    description: 'The target url'
  method:
    description: 'The request method, basically one of GET, POST, PUT, PATCH'
    default: 'GET'
  accept:
    description: 'List of status codes to be accepted, else it is considerred to be failed'
    default: 200,201,204
  headers:
    description: 'Headers object'
  params:
    description: 'Params object'
  body:
    description: 'Body object'
  send-raw-body:
    description: 'Send raw body instead of JSON-parsed or YAML-parsed body'
    default: 'false'
  timeout:
    description: 'timeout (millisec)'
    default: 1000
  basic-auth-token:
    description: 'Basic authentication token, format => username:password as base64'
  bearer-token: 
    description: 'Bearer Token'
  proxy-url:
    description: 'Proxy host, format => host:port'
  proxy-auth-token: 
    description: 'Proxy authentication token, format =>  username:password as base64'
  log-response: 
    description: 'Should log the response'
    default: 'false'
  retries:
    description: 'Number of retries'
    default: 1
  custom-config:
    description: custom config

outputs:
  response:
    description: 'The response object'
branding:
  icon: 'download'  
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
